// Mocks generated by Mockito 5.4.6 from annotations
// in idle_hippo/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/foundation.dart' as _i2;
import 'package:idle_hippo/models/game_state.dart' as _i4;
import 'package:idle_hippo/services/config_service.dart' as _i6;
import 'package:idle_hippo/services/game_state_service.dart' as _i3;
import 'package:idle_hippo/services/idle_income_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GameStateService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameStateService extends _i1.Mock implements _i3.GameStateService {
  MockGameStateService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueNotifier<_i4.GameState> get gameState =>
      (super.noSuchMethod(
            Invocation.getter(#gameState),
            returnValue: _FakeValueNotifier_0<_i4.GameState>(
              this,
              Invocation.getter(#gameState),
            ),
          )
          as _i2.ValueNotifier<_i4.GameState>);

  @override
  set gameState(_i2.ValueNotifier<_i4.GameState>? _gameState) =>
      super.noSuchMethod(
        Invocation.setter(#gameState, _gameState),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateGameState(_i4.GameState? newState) =>
      (super.noSuchMethod(
            Invocation.method(#updateGameState, [newState]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> initializeForTest(_i4.GameState? initialState) =>
      (super.noSuchMethod(
            Invocation.method(#initializeForTest, [initialState]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i6.ConfigService {
  MockConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoaded =>
      (super.noSuchMethod(Invocation.getter(#isLoaded), returnValue: false)
          as bool);

  @override
  Map<String, dynamic> get allConfigs =>
      (super.noSuchMethod(
            Invocation.getter(#allConfigs),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.Future<void> loadConfig() =>
      (super.noSuchMethod(
            Invocation.method(#loadConfig, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  dynamic getValue(String? path, {dynamic defaultValue}) => super.noSuchMethod(
    Invocation.method(#getValue, [path], {#defaultValue: defaultValue}),
  );

  @override
  _i5.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  Map<String, dynamic>? getPetConfig(String? petKey) =>
      (super.noSuchMethod(Invocation.method(#getPetConfig, [petKey]))
          as Map<String, dynamic>?);

  @override
  Map<String, dynamic>? getPetRarityConfig(String? petKey, String? rarityKey) =>
      (super.noSuchMethod(
            Invocation.method(#getPetRarityConfig, [petKey, rarityKey]),
          )
          as Map<String, dynamic>?);
}

/// A class which mocks [IdleIncomeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdleIncomeService extends _i1.Mock implements _i7.IdleIncomeService {
  MockIdleIncomeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get totalIdleTime =>
      (super.noSuchMethod(Invocation.getter(#totalIdleTime), returnValue: 0.0)
          as double);

  @override
  double get totalIdleIncome =>
      (super.noSuchMethod(Invocation.getter(#totalIdleIncome), returnValue: 0.0)
          as double);

  @override
  double get currentIdlePerSec =>
      (super.noSuchMethod(
            Invocation.getter(#currentIdlePerSec),
            returnValue: 0.0,
          )
          as double);

  @override
  void setTestingIdlePerSec(double? value) => super.noSuchMethod(
    Invocation.method(#setTestingIdlePerSec, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateGameState(_i4.GameState? gameState) => super.noSuchMethod(
    Invocation.method(#updateGameState, [gameState]),
    returnValueForMissingStub: null,
  );

  @override
  void init({void Function(double)? onIncomeGenerated}) => super.noSuchMethod(
    Invocation.method(#init, [], {#onIncomeGenerated: onIncomeGenerated}),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetStats() => super.noSuchMethod(
    Invocation.method(#resetStats, []),
    returnValueForMissingStub: null,
  );

  @override
  void enableTestingMode(bool? enabled) => super.noSuchMethod(
    Invocation.method(#enableTestingMode, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void onTickForTest(double? deltaSeconds) => super.noSuchMethod(
    Invocation.method(#onTickForTest, [deltaSeconds]),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getStats() =>
      (super.noSuchMethod(
            Invocation.method(#getStats, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
